### ISSUE TITLE
Many endpoints at "auth" - doesn't line up with GIF example

### ISSUE THREAD

**Issue by SootyOwl** [eadwinCode/bookstoreapi#1]
Hello, I'm attempting to use this repository as a guideline for implementing JWT Authentication in Django-Ninja. However, I'm running into one issue: when viewing the API docs, there are *many* `Obtain Token` and `Refresh Token` API endpoints appearing, despite the UserTokenController only implementing one.

***Steps to reproduce***
1. Clone this repository
2. Build `bash scripts/docker_build.sh build`
3. Run `bash scripts/docker_build.sh up`
4. Navigate to http://0.0.0.0:8001/api/docs
5. Scroll to "auth" section

***Expected***
Two API endpoints are listed in the "auth" section, one "Obtain Token" endpoint and one "Refresh Token" endpoint, matching the example .GIF in the README. 

***Actual***
_Six_ endpoints are listed in the "auth" section, three "Obtain Token" and three "Refresh Token".
![image](https://user-images.githubusercontent.com/7614538/160147830-e64638a4-4a9e-435c-972a-a4eea61e2041.png)

**Comment by eadwinCode** [comment]
@SootyOwl 
Its fixed now. Just update django-ninja-extra package

**Comment by eadwinCode** [comment]
@SootyOwl update released

**Comment by SootyOwl** [comment]
Excellent thank you, I can confirm that after updating `django-ninja-extra` the issue is resolved both in this repository and my own project.
